/**
 * ------------------------------------------------------------------
 * Payfolo Email Layout
 * ------------------------------------------------------------------
 * Shared HTML layout for all notification emails.
 *
 * This file should ONLY be responsible for the overall email design.
 * Notification-specific content is injected through the `content`
 * parameter.
 * ------------------------------------------------------------------
 */

export function renderEmailLayout({
  title = "Notification",
  bannerColor = "#2563EB",
  companyName = "Payfolo",
  logoUrl = "",
  content = "",
  senderCompany = "",
  senderEmail = "",
  senderPhone = "",
}) {
  return `
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta
  name="viewport"
  content="width=device-width, initial-scale=1.0"
/>

<title>${title}</title>

</head>

<body
  style="
    margin:0;
    padding:28px 28px 0;
    background:#F3F6FB;
    font-family:Arial,Helvetica,sans-serif;
  "
>

<table
  width="100%"
  cellpadding="0"
  cellspacing="0"
  border="0"
>

<tr>

<td align="center">

<table
  width="600"
  cellpadding="0"
  cellspacing="0"
  border="0"
  style="
    background:#ffffff;
    border-radius:12px;
    overflow:hidden;
    box-shadow:0 4px 20px rgba(0,0,0,.08);
  "
>

<!-- ====================================================== -->
<!-- Header -->
<!-- ====================================================== -->

<tr>

<td
  style="
    background:${bannerColor};
    padding:30px;
    color:#ffffff;
  "
>

<table width="100%">

<tr>

<td align="left">

${`<div
  style="
  font-size:28px;
  font-weight:bold;
  "
  >
        ${companyName}
  </div>`}

</td>

</tr>

</table>

</td>

</tr>

<!-- ====================================================== -->
<!-- Body -->
<!-- ====================================================== -->

<tr>

<td
  style="
    padding:28px 28px;
    color:#334155;
    font-size:15px;
    line-height:1.5;
  "
>

${content}

</td>

</tr>

<!-- ====================================================== -->
<!-- Footer -->
<!-- ====================================================== -->

<tr>

<td
  style="
    padding:18px 28px;
    background:#F8FAFC;
    border-top:1px solid #E2E8F0;
  "
>

<div
  style="
    margin-top:20px;
    font-size:12px;
    color:#94A3B8;
  "
>

This is an automated notification generated by Payfolo.
Please do not reply directly to this email.

</div>

</td>

</tr>

</table>

</td>

</tr>

</table>

</body>

</html>
`;
}
